import type { DesignMode, DesignPurpose, DesignVariant } from './types';

export const designPurposeOrder: DesignPurpose[] = [
  'theme-wrapper',
  'nav-container',
  'active-tab',
  'card',
  'label',
  'button-primary',
  'button-secondary',
  'button-icon',
  'input-field',
  'input-range',
  'status-indicator',
  'surface',
  'layout-container',
  'feature-container',
];

export const designVariants: Record<DesignMode, DesignVariant> = {
  lab: {
    mode: 'lab',
    label: 'Laboratory',
    environment: 'Technical precision and data-first interfaces',
    source: 'emotional-systems',
    goal: 'competence',
    feeling: 'precision',
    purposeStyles: {
      'theme-wrapper': 'bg-[#F0F4F8] text-[#0F172A] font-mono selection:bg-[#FF4500] selection:text-white',
      'nav-container': 'bg-[#E2E8F0] rounded-none',
      'active-tab': 'bg-[#0F172A] text-white shadow-none font-mono text-xs tracking-wider',
      card: 'bg-white border border-[#CBD5E1] shadow-none rounded-none relative',
      label: 'font-mono text-[10px] uppercase tracking-widest text-[#64748B]',
      'button-primary':
        'bg-[#0F172A] text-white font-mono text-xs py-3 uppercase tracking-wider hover:bg-[#FF4500] transition-colors',
      'button-secondary':
        'bg-transparent border border-[#94A3B8] text-[#475569] font-mono text-xs hover:border-[#0F172A] transition-colors',
      'button-icon': 'border border-[#CBD5E1] bg-white hover:border-[#0F172A] text-[#0F172A]',
      'input-field': 'bg-transparent border border-[#CBD5E1] text-[#0F172A] font-mono text-sm focus:border-[#0F172A]',
      'input-range': 'accent-[#FF4500] h-1 bg-gray-200 rounded-none appearance-none cursor-pointer',
      'status-indicator': 'w-16 h-16 border-2 border-[#0F172A] bg-white text-[#0F172A]',
      surface: 'bg-[#F8FAFC] border border-[#CBD5E1] shadow-none',
      'layout-container': 'bg-white border border-[#CBD5E1]',
      'feature-container': 'bg-white border-y border-[#CBD5E1]',
    },
  },
  pop: {
    mode: 'pop',
    label: 'Playground',
    environment: 'Playful interactions and high energy surfaces',
    source: 'emotional-systems',
    goal: 'joy',
    feeling: 'euphoria',
    purposeStyles: {
      'theme-wrapper': 'bg-[#FFFAEB] text-[#2E1065] font-sans selection:bg-[#D946EF] selection:text-white',
      'nav-container': 'bg-white rounded-full shadow-sm border border-gray-100',
      'active-tab': 'bg-[#D946EF] text-white rounded-full shadow-md font-bold transform -translate-y-1',
      card: 'bg-white rounded-3xl shadow-[8px_8px_0px_#E0E7FF] border-2 border-[#E0E7FF]',
      label: 'font-bold text-sm uppercase text-[#818CF8] tracking-wide',
      'button-primary':
        'bg-[#8B5CF6] text-white font-bold py-3 rounded-xl shadow-[0_4px_0_#7C3AED] hover:translate-y-1 hover:shadow-none transition-all active:bg-[#6D28D9]',
      'button-secondary': 'bg-[#F3F4F6] text-[#4B5563] font-bold rounded-xl hover:bg-[#E5E7EB] transition-colors',
      'button-icon':
        'bg-[#22D3EE] text-white rounded-full shadow-[0_4px_0_#0891B2] hover:translate-y-1 hover:shadow-none transition-all',
      'input-field': 'bg-white border-2 border-[#E0E7FF] rounded-xl text-[#2E1065] focus:border-[#D946EF]',
      'input-range': 'accent-[#D946EF] h-4 bg-gray-100 rounded-full appearance-none cursor-pointer',
      'status-indicator': 'w-16 h-16 bg-[#FACC15] text-[#2E1065] rounded-2xl shadow-[4px_4px_0px_#CA8A04] animate-pulse',
      surface: 'bg-[#E0E7FF] rounded-3xl',
      'layout-container': 'bg-white m-4 rounded-3xl border-2 border-[#E0E7FF]',
      'feature-container': 'bg-white m-4 rounded-3xl border-2 border-[#E0E7FF]',
    },
  },
  zen: {
    mode: 'zen',
    label: 'Sanctuary',
    environment: 'Calm, soft, and restorative interfaces',
    source: 'emotional-systems',
    goal: 'peace',
    feeling: 'serenity',
    purposeStyles: {
      'theme-wrapper': 'bg-[#EBE9E4] text-[#44403C] font-sans selection:bg-[#A8A29E] selection:text-white',
      'nav-container': 'bg-[#E5E2DC] rounded-full',
      'active-tab': 'bg-white text-[#57534E] rounded-full shadow-sm',
      card: 'bg-white/60 backdrop-blur-md rounded-2xl shadow-sm border border-white/40',
      label: 'font-serif italic text-sm text-[#78716C]',
      'button-primary': 'bg-[#D6D3CD] text-[#44403C] py-3 rounded-lg hover:bg-[#C8C5BE] transition-colors duration-500',
      'button-secondary': 'bg-transparent text-[#78716C] hover:text-[#44403C] transition-colors',
      'button-icon': 'bg-white text-[#78716C] rounded-full shadow-sm hover:shadow-md transition-shadow',
      'input-field': 'bg-white/70 border border-white/40 rounded-lg text-[#44403C] focus:border-[#A8A29E]',
      'input-range': 'accent-[#A8A29E] h-1 bg-[#D6D3CD] rounded-full appearance-none cursor-pointer',
      'status-indicator': 'w-16 h-16 bg-gradient-to-br from-white to-[#E7CBA9] rounded-full shadow-inner text-[#78716C]',
      surface: 'bg-white/50 border border-white/40 rounded-2xl shadow-inner',
      'layout-container': 'bg-white/40 rounded-3xl',
      'feature-container': 'bg-white/40 rounded-3xl',
    },
  },
  museum: {
    mode: 'museum',
    label: 'Museumcore',
    environment: 'Editorial heritage, tactile warmth, and typographic gravitas',
    source: 'design-research-1',
    goal: 'permanence',
    feeling: 'reverence',
    purposeStyles: {
      'theme-wrapper': 'bg-[#F7F5F0] text-[#2C2825] font-serif selection:bg-[#8A3324] selection:text-white',
      'nav-container': 'bg-black/5 dark:bg-white/5 rounded-full md:rounded-lg',
      'active-tab': 'bg-[#2C2825] text-[#F7F5F0] rounded-full font-serif italic',
      card: 'bg-white border border-[#D1CDC7] shadow-sm',
      label: 'text-xs uppercase tracking-widest opacity-50',
      'button-primary':
        'bg-[#2C2825] text-[#F7F5F0] py-3 px-6 text-sm tracking-widest uppercase hover:opacity-90 transition-opacity',
      'button-secondary':
        'bg-transparent text-[#2C2825] border border-[#2C2825] py-3 px-6 text-sm tracking-widest uppercase hover:bg-[#2C2825] hover:text-[#F7F5F0] transition-colors',
      'button-icon': 'border border-[#2C2825] bg-[#F2F0EB] text-[#2C2825] rounded-full hover:bg-white transition-colors',
      'input-field': 'border-b border-[#2C2825] focus:border-b-2 placeholder:italic placeholder:opacity-50',
      'input-range': 'accent-[#8A3324] h-1 bg-[#D1CDC7] rounded-none appearance-none cursor-pointer',
      'status-indicator': 'w-16 h-16 border border-[#2C2825] bg-[#E6E2D6] text-[#2C2825] rounded-full',
      surface: 'bg-[#F0EEE6] border border-[#D1CDC7] shadow-inner',
      'layout-container': 'bg-[#F2F0EB] border border-[#D1CDC7]',
      'feature-container': 'bg-[#F2F0EB] border border-[#D1CDC7]',
    },
  },
  brutal: {
    mode: 'brutal',
    label: 'Neo Brutalist',
    environment: 'Raw contrast, hard edges, and anti-polish interaction language',
    source: 'design-research-1',
    goal: 'rebellion',
    feeling: 'defiance',
    purposeStyles: {
      'theme-wrapper': 'bg-[#FFFDF5] text-black font-mono selection:bg-black selection:text-[#CCFF00]',
      'nav-container': 'bg-black/5 dark:bg-white/5 rounded-full md:rounded-lg',
      'active-tab': 'bg-[#FF3366] text-white font-bold border-2 border-black shadow-[2px_2px_0px_0px_black] -translate-y-1',
      card: 'bg-white border-4 border-black shadow-[8px_8px_0px_0px_black]',
      label: 'text-xs uppercase tracking-widest opacity-50 font-mono font-bold',
      'button-primary':
        'bg-[#CCFF00] text-black border-2 border-black font-bold py-3 px-6 shadow-[4px_4px_0px_0px_black] hover:translate-y-[2px] hover:translate-x-[2px] hover:shadow-[2px_2px_0px_0px_black] active:shadow-none transition-all',
      'button-secondary':
        'bg-white text-black border-2 border-black font-bold py-3 px-6 shadow-[4px_4px_0px_0px_black] hover:translate-y-[2px] hover:translate-x-[2px] hover:shadow-[2px_2px_0px_0px_black] active:shadow-none transition-all',
      'button-icon': 'bg-black text-white border-2 border-black shadow-[4px_4px_0px_0px_black] hover:translate-y-[2px] hover:translate-x-[2px] hover:shadow-none transition-all',
      'input-field': 'bg-white border-2 border-black font-mono focus:bg-[#FFF0F5] placeholder:uppercase placeholder:text-black/40',
      'input-range': 'accent-[#FF3366] h-3 bg-white border-2 border-black rounded-none appearance-none cursor-pointer',
      'status-indicator': 'w-16 h-16 bg-[#CCFF00] border-4 border-black text-black shadow-[4px_4px_0px_0px_black]',
      surface: 'bg-[#0000FF] border-4 border-black text-white',
      'layout-container': 'bg-white border-4 border-black pattern-grid-lg',
      'feature-container': 'bg-white border-4 border-black',
    },
  },
  immersive: {
    mode: 'immersive',
    label: 'Immersive',
    environment: 'Layered depth, glow, blur, and simulation-driven UI surfaces',
    source: 'design-research-1',
    goal: 'immersion',
    feeling: 'transcendence',
    purposeStyles: {
      'theme-wrapper': 'bg-[#050505] text-white font-sans selection:bg-cyan-500 selection:text-black',
      'nav-container': 'bg-black/5 dark:bg-white/5 rounded-full md:rounded-lg',
      'active-tab': 'bg-white/10 text-cyan-400 backdrop-blur-md rounded-lg shadow-[0_0_15px_rgba(0,255,255,0.3)] border border-white/10',
      card: 'bg-white/5 border border-white/10 backdrop-blur-lg rounded-3xl shadow-2xl',
      label: 'text-xs uppercase tracking-widest opacity-50',
      'button-primary':
        'bg-cyan-500/20 text-cyan-300 border border-cyan-500/50 py-3 px-6 rounded-full font-medium hover:bg-cyan-500/30 hover:shadow-[0_0_20px_rgba(6,182,212,0.4)] transition-all',
      'button-secondary':
        'bg-white/5 text-white border border-white/10 py-3 px-6 rounded-full font-medium hover:bg-white/10 transition-all',
      'button-icon':
        'bg-white/10 text-cyan-300 border border-white/20 rounded-full backdrop-blur-md hover:bg-white/20 transition-colors',
      'input-field':
        'bg-white/5 border border-white/10 rounded-xl focus:bg-white/10 focus:border-cyan-500/50 transition-colors placeholder:text-white/30',
      'input-range': 'accent-cyan-400 h-2 bg-white/10 rounded-full appearance-none cursor-pointer',
      'status-indicator': 'w-16 h-16 bg-cyan-500/20 border border-cyan-500/50 rounded-full shadow-[0_0_20px_rgba(6,182,212,0.35)] text-cyan-300',
      surface: 'bg-white/10 border border-white/20 backdrop-blur-md rounded-2xl shadow-[0_8px_32px_0_rgba(31,38,135,0.37)]',
      'layout-container': 'bg-black border border-white/10 rounded-3xl overflow-hidden relative',
      'feature-container': 'bg-black/60 border border-white/10 rounded-3xl backdrop-blur-md',
    },
  },
};
